### PR TITLE
Fix #2494 Error when saving style for flatgeobuff dataset

### LINKED ISSUE #2494: Error when saving the style for a FlatGeoBug dataset
When the style for a FlatGeoBuf (remote) dataset is changed and saved, the client tries to save the style to Geoserver.
This is wrong because the layer isn't a Geoserver layer, and there's no style for it in Geoserver.

The style for FGBs (as well as for any non-Geoserver layer, like COGs and 3dtiles) must not trigger a save in Geoserver.

The following image shows the wrong request sent by the client to Geoserver. Notice that the path is also wrong. It uses /catalog instead of /geoserver

Image

### PR DESCRIPTION
**Pull request by subashtiwari1010**
## Related tasks

Fixes https://github.com/GeoNode/geonode-mapstore-client/issues/2494

## Describe this PR

This PR fixes save behavior for non-GeoServer dataset formats like FlatGeoBuf, COG, and 3dtiles.

Previously, changing the style of a remote FlatGeoBuf dataset and clicking save caused the client to send a GeoServer REST request to persist the default style. That is incorrect because these formats do not store styling in GeoServer. In some cases, this also produced an invalid request such as /catalogue/rest/layers/undefined.json.

### Changes

- Skip GeoServer default-style updates for unsupported non-GeoServer layer formats during save
- Keep the normal save flow unchanged for GeoServer-backed layers
- Add a test for FlatGeoBuf save

### CODE REVIEW

File: geonode_mapstore_client/client/js/epics/gnsave.js [hunk 1]
```diff
@@ -109,8 +109,21 @@ function parseMapBody(body) {
...
 
+/**
+ * Check if the selected layer can persist its default style through GeoServer REST.
+ * Only default GeoNode dataset subtypes support this workflow.
+ * @param {object} layer Selected layer configuration.
+ * @param {string} subtype Current dataset subtype.
+ * @returns {boolean} True when the layer supports GeoServer default-style updates.
+ */
+const isGeoServerStyleUpdateAllowed = (layer = {}, subtype) => {
+    return isDefaultDatasetSubtype(subtype)
```
Comment (allyoucanmap) [inline geonode_mapstore_client/client/js/epics/gnsave.js]: the isDefaultDatasetSubtype includes also `remote` but this should not included in the style save workflow

**Review by allyoucanmap — CHANGES_REQUESTED** [review]

**Review by allyoucanmap — APPROVED** [review]
